version = 0.1
[default.deploy.parameters]
stack_name = "PmdApi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fjorkcfscj85"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
s3_prefix = "PmdApi"
confirm_changeset = false
